services:
  default: &default
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    build:
      context: .
      args: &default-args
        TARGET_IMAGE: alpine
    volumes_from:
      - exercism-config
    working_dir: /home/exercist/exercism
    environment: &default-env
      HOME: /home/exercist

  exercism-config:
    image: alpine
    volumes:
      - $HOME/.config:/home/exercist/.config
      - .:/home/exercist/exercism

  elixir:
    <<: *default
    build:
      args:
        <<: *default-args
        TARGET_IMAGE: "elixir:alpine"
    working_dir: /home/exercist/exercism/elixir

  java:
    <<: *default
    build:
      args:
        <<: *default-args
        TARGET_IMAGE: "eclipse-temurin:25-alpine"
    working_dir: /home/exercist/exercism/java
    entrypoint: ["/docker/java-entrypoint.sh"]
    volumes:
      - ./docker/java-entrypoint.sh:/docker/java-entrypoint.sh:ro
      - $HOME/.gradle:/home/exercist/.gradle

  ruby:
    <<: *default
    build:
      args:
        <<: *default-args
        TARGET_IMAGE: "ruby:alpine"
    working_dir: /home/exercist/exercism/ruby
